### ISSUE TITLE
Not grabbing backtick codeblocks (markdown)

### ISSUE THREAD

**Issue by plttn** [philpl/Adventurous-Syntax#1]
![2015-01-09_23-25-38](https://cloud.githubusercontent.com/assets/7369280/5690774/da234d94-9856-11e4-86ef-a869010dcdb8.png) compared to seti: ![2015-01-09_23-26-16](https://cloud.githubusercontent.com/assets/7369280/5690775/ecaf573c-9856-11e4-95bc-11fbab46f08a.png)

Tried fixing it myself, wasn't sure of the exact syntax.

**Comment by ralyodio** [comment]
better served indenting 4 spaces for code blocks in markdown.

**Comment by plttn** [comment]
I use octopress, which recognizes GFM style backtick code blocks.

**Comment by ralyodio** [comment]
I've had problems with triple backticks in other markdown editors. But `<tab>` (4 spaces) always works.

edit: not saying its not a bug, just if you need to move forward, tabs will work.

**Comment by plttn** [comment]
Considering that other themes are willing to highlight it, it's definitely a bug.

**Comment by kitten** [comment]
I'll try to get this to work :smile:
