### ISSUE TITLE
Vim/Iterm2

### ISSUE THREAD

**Issue by bhargavrpatel** [philpl/Adventurous-Syntax#8]
Any chance this can be ported to work with vim in iterm2 with zshell?

**Comment by kitten** [comment]
I've just created a syntax which applies these colours programmatically. It's still a work in progress, but it generates a nice enough theme.

It's built on my custom-modified Dracula theme and searches for similar colours.

Sorry for the delay ;P

https://github.com/philpl/vim-adventurous
